services:
  test-db:
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    volumes:
      - test-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalog_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  test-opensearch:
    image: opensearchproject/opensearch:3
    container_name: test-opensearch
    environment:
      - cluster.name=test-opensearch-cluster
      - node.name=test-opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - test-opensearch-data:/usr/share/opensearch/data
    ports:
      - 9201:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  test-db-data:
  test-opensearch-data: